version: '3'

services:

  broker-service:
    build:
      context: https://github.com/fcisnerosrojo/go-micro-broker-service
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1